baseURL: http://example.org/
languageCode: en-us
title: rredlich - back to coding
theme: "PaperMod"

params:
    defaultTheme: dark
    disableThemeToggle: false
    ShowReadingTime: true
    homeInfoParams:
        Title: Hola  Rodolfo por ac谩...
        Content: En 2013 co-fund茅 zembia.cl, una empresa de desarrollo tecnol贸gico, y parad贸jicamente me alej茅 de la programaci贸n. En este espacio documento mi vuelta al c贸digo y mi ruta de aprendizaje para desarrollo full-stack.

    socialIcons:
        - name: twitter
          url: "https://twitter.com/rojolich"
        - name: instagram
          url: "https://www.instagram.com/rojolich/"
        - name: linkedin
          url: "https://www.linkedin.com/in/rredlich/"
        - name: github
          url: "https://github.com/rredlich"

