baseURL: https://rredlich.github.io/
languageCode: en-us
title: rredlich - back to coding
theme: "PaperMod"

taxonomies:
  tag: tags

params:
    title: rredlich
    description: "P谩gina personal donde comparto contenido de mi aprendizaje en el desarrollo full-stack."
    author: Rodolfo Redlich

    assets:
        favicon: "icons/favicon.ico"
        favicon16x16: "icons/favicon-16x16.png"
        favicon32x32: "icons/favicon-32x32.png"
        apple_touch_icon: "icons/apple-touch-icon.png"
        android-chrome: "icons/android-chrome-192x192.png"
        android-chrome: "icons/android-chrome-512x512.png"

    defaultTheme: dark
    disableThemeToggle: false
    ShowReadingTime: true

    homeInfoParams:
        Title: Hola  Rodolfo por ac谩...
        Content: En 2013 co-fund茅 zembia.cl, una empresa de desarrollo tecnol贸gico, y parad贸jicamente me alej茅 de la programaci贸n. En este espacio documento mi vuelta al c贸digo y mi ruta de aprendizaje para desarrollo full-stack.

    socialIcons:
        - name: twitter
          url: "https://twitter.com/rojolich"
        - name: instagram
          url: "https://www.instagram.com/rojolich/"
        - name: linkedin
          url: "https://www.linkedin.com/in/rredlich/"
        - name: github
          url: "https://github.com/rredlich"

